paramters:
  dispatcher.separator: '.'

services:
  app.mvc.phalcon:
    class: Phalcon\Mvc\Application
    arguments: ['@app.di']
  app.http.phalcon:
    decorates: app.http
    decoration_priority: 1000
    class: Vainyl\Phalcon\Application\Decorator\PhalconApplicationDecorator
    arguments: ['@app.http.phalcon.inner', '@app.mvc.phalcon', '@response.stack.phalcon']
  router.phalcon:
    class: Phalcon\Mvc\Router
  router: '@router.phalcon'
  view.phalcon:
    class: Phalcon\Mvc\View
  view: '@view.phalcon'
  dispatcher.phalcon:
    class: Vain\Phalcon\Dispatcher\Mvc\MvcDispatcher
    arguments: ['%dispatcher.separator%']
    calls:
      - [setEventsManager, ['@event.dispatcher.phalcon']]
      - [setParams, [[]]]
  dispatcher: '@dispatcher.phalcon'
  response: '@response.stack'
  filter.phalcon:
    class: Phalcon\Filter
  bootstrapper.di:
    class: Vainyl\Phalcon\Application\DiBootstrapper
    arguments: ['@app.di']
    tags:
        - {name: bootstrapper}
  bootstrapper.router:
    class: Vainyl\Phalcon\Application\RouterBootstrapper
    arguments: ['@router.phalcon']
    tags:
        - {name: bootstrapper}
  event.dispatcher.phalcon:
    decorates: event.dispatcher
    class: Vainyl\Phalcon\Event\PhalconEventDispatcher
    arguments: ['@event.dispatcher.phalcon.inner']
  database.factory.phalcon:
    class: Vainyl\Pdo\Factory\PdoDatabaseFactory
    arguments: ['@connection.storage']
  request.stack.phalcon:
    decorates: request.stack
    class: Vainyl\Phalcon\Http\Stack\PhalconRequestStack
    arguments: ['@request.stack.phalcon.inner']
  response.stack.phalcon:
    decorates: response.stack
    class: Vainyl\Phalcon\Http\Stack\PhalconResponseStack
    arguments: ['@response.stack.phalcon.inner']
  cookie.factory.phalcon:
    decorates: cookie.factory
    class: Vainyl\Phalcon\Http\Factory\PhalconCookieFactory
    arguments: ['@cookie.factory.phalcon.inner', '@time.factory']
  file.factory.phalcon:
    decorates: file.factory
    class: Vainyl\Phalcon\Http\Factory\PhalconFileFactory
    arguments: ['@file.factory.phalcon.inner']
  request.factory.phalcon:
    decorates: request.factory
    class: Vainyl\Phalcon\Http\Factory\PhalconRequestFactory
    arguments: ['@request.factory.phalcon.inner', '@filter.phalcon']
  response.factory.phalcon:
    decorates: response.factory
    class: Vainyl\Phalcon\Http\Factory\PhalconResponseFactory
    arguments: ['@response.factory.phalcon.inner']
  model.manager:
    class: Vainyl\Phalcon\Mvc\PhalconModelManager
  dispatcher.mvc.phalcon:
    class: Vainyl\Phalcon\Mvc\PhalconMvcDispatcher
  query.builder:
    class: Vainyl\Phalcon\Mvc\PhalconMvcQueryBuilder
  controller.phalcon.abstract:
    abstract: true
    calls:
      - [initialize, ['@encoder.storage']]